### ISSUE TITLE
Question about `if` statement in `editLedger` method

### ISSUE THREAD

**Issue by ambujsahu81** [fregante/delegate-it#37]
In the following code on line 39 , it seems that `ledger.has(baseElement)` will always be true. Since on line 37 base element was added to ledger.  And hence it makes the whole expression `(!wanted && !ledger.has(baseElement))` to be always false.

It seems that the if statement might not be required ?

https://github.com/fregante/delegate-it/blob/e412983f097ddfdccdb23bad6c5eb742e9da963a/index.ts#L37-L41

**Comment by fregante** [comment]
Thank you for the review! Indeed I think it was a mistake in https://github.com/fregante/delegate-it/commit/9624053b1ec1515a52ce42da16497bf3cb89311f

I'm not sure if the intent has always been to check the existence in the elements map rather than directly in the ledger. But yeah until now that line is always false
